### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by herrartist** [Limbicnation/TransformDepth#8]
No matter how I call the path. I always get a syntax error:
SyntaxError: invalid syntax
File "DepthEstimationPipeline.py", line 27
depth_image.save(C:Users\mail\Desktop\TransformDepth-main\output)

Your video tutorial is very unclear how to write a correct path for single and batch processing.

**Comment by Limbicnation** [comment]
> No matter how I call the path. I always get a syntax error: SyntaxError: invalid syntax File "DepthEstimationPipeline.py", line 27 depth_image.save(C:Users\mail\Desktop\TransformDepth-main\output)
> 
> Your video tutorial is very unclear how to write a correct path for single and batch processing.

Hello @herrartist,

The error you're encountering is due to an incorrect path format. In Python, file paths must be enclosed in quotes and use either double backslashes (`\\`) or forward slashes (`/`). Here's how you can correctly specify the path:

```python
depth_image.save("C:\\Users\\mail\\Desktop\\TransformDepth-main\\output")
```

or

```python
depth_image.save("C:/Users/mail/Desktop/TransformDepth-main/output")
```

Make sure to use the correct syntax for both single and batch processing. Here’s an example command for processing a single image:

```bash
python DepthEstimationPipeline.py --single "C:\\path\\to\\your\\image.png" --output "C:\\path\\to\\output\\directory"
```

And for batch processing:

```bash
python DepthEstimationPipeline.py --batch "C:\\path\\to\\your\\image_directory" --output "C:\\path\\to\\output\\directory"
```

Remember to always enclose your paths in quotes and use the correct path separators.

Additionally, please ensure your repository is up to date, since I've updated the model to ```depth-anything-v2``` by running:

```bash
git pull
pip install -r requirements.txt
```

If the issue persists, you can start fresh by creating a new Python environment with the following commands:

```bash
conda create -n depth-anything-2 python=3.11.9
conda activate depth-anything-v2
```

I will provide a video tutorial soon to further assist with these steps.
